### ISSUE TITLE
[Bug] Email push notifications unable to distinguish between read and unread

### ISSUE THREAD

**Issue by jeanpierrevanzyl** [ProtonMail/proton-mail-android#109]
**Describe the bug**
Push notifications show a list of emails which you have not opened from a previous push notification, instead of showing your unread emails

**To Reproduce**
1. Receive email
2. DO NOT click on push notification, swipe it away
3. Open ProtonMail app
4. Read email and close
5. Receive second email
6. The push notification will contain the new email as well as the previously received (and already read) email

**Expected behavior**
Push notifications should show only unread emails

**Smartphone:**
 - Device: Xiaomi Redmi Note 8
 - OS: LineageOS 17.1 with MicroG (Android 10)
 - Kernel Version: 4.14.117

**Comment by 4n0nym0u53** [comment]
This also happens when receiving an email notification on the phone, swiping it away, reading it on the web (hence it's marked as read) and then receiving another email.

**Comment by turb** [comment]
We should also expect to have a notification removed if the email is marked as read elsewhere, even if the notification has not been swiped away (this is the behaviour of most emailing/messaging apps).

**Comment by coderecruit** [comment]
This is still an ongoing issue and becomes more annoying as I use Proton more and more. Would be lovely to see this fixed :)

**Comment by jeanpierrevanzyl** [comment]
This behaviour seems to have been fixed in the latest stable update.
Even as far as opening an email in a browser, swiping away the notification and receiving a new email behaves correctly
Many thanks to the devs
