### ISSUE TITLE
Checking mailbox notification

### ISSUE THREAD

**Issue by mKoonrad** [ProtonMail/proton-mail-android#11]
App show additional Checking mailbox notification (for a few seconds) every time when I receive new message. It's notification from Ongoing operations channel. I shouldn't see any additional, temporary notification.

Tested on OnePlus 5T, Android 9, ProtonMail app version 1.13.4 (717) also after fresh app reinstall. I saw this problem also in earlier app versions.

**Comment by 4face-studi0** [comment]
Not 100% sure whether we are talking about the same thing, but that might be a Service that is running in background for decrypt the email, so Android Oreo+ requires a Service to be bring in foreground trough a notification

**Comment by mKoonrad** [comment]
@4face-studi0 It's first notification on top
![Screenshot_20200427-152804__01](https://user-images.githubusercontent.com/11725227/80378008-52951880-889c-11ea-8169-5adb51ce9d8a.jpg)

**Comment by 4face-studi0** [comment]
This should be quick and disappear after about one second, isn't that the case? This notification cannot be avoided, since as said, is needed to bring the service in foreground:
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/java/ch/protonmail/android/gcm/GcmIntentService.java#L100-L104

What you can do is make the notification channel silent from the Android's Notification settings

**Comment by mKoonrad** [comment]
@4face-studi0 Thanks for info. Yes - it disappear after moment. For user is strange. Most apps don't need additional notification. Can you make this notification channel silent by default?

**Comment by 4face-studi0** [comment]
Yes, we could ( maybe somebody already did it, not sure ) but by Android design, after a channel is created, only the user can change it. The only way we have is to create a new channel and delete the old one, but in that case we should evaluate if it would be the proper way

**Comment by TeChn4K** [comment]
In my case, I have as much notification as unread email

<img src="https://i.ibb.co/7pBgFfN/Screenshot-protonmail-notifs.jpg" height="400" >

**Comment by TeChn4K** [comment]
In my case, I have as much notification as unread message

<img src="https://i.ibb.co/RCkbH98/Screenshot-protonmail-notifs.jpg" height="400" />
