### ISSUE TITLE
[Feature Request] Notification configuration for specific labels and folders

### ISSUE THREAD

**Issue by justinfiore** [ProtonMail/proton-mail-android#111]
**Is your feature request related to a problem? Please describe.**
I like most people receive too many emails to make being notified on every email useful. 
Please implement settings similar to Gmail Android app where you can configure which labels and folders triggers notifications. 

**Describe the solution you'd like**
Allow configuration of which labels and folders will trigger a push notification. 
Only show notifications in that set of configured folders and labels. Any notifications not matching that set should be not sent ( or filtered out at client side if that isn't possible)

**Describe alternatives you've considered**
None. I don't see any options to do this. 

**Additional context**

**Comment by bartbutler** [comment]
You can do this here (web client) and, combined with filters that file your mail, your problem should be solved: https://account.protonmail.com/u/0/mail/folders-labels

**Comment by justinfiore** [comment]
@bartbutler I can see you can configure notifications at the folder level, but I don't see similar configuration for notifications at the label level. 
It is really important to have at the label level as a given email can have multiple labels, one of which may have a notification. 

![Screenshot_20210816-183211_Vivaldi](https://user-images.githubusercontent.com/1559631/129645623-c4b00c8f-8206-442d-8c84-f7f9f21c1a82.jpg)

**Comment by bartbutler** [comment]
I think in the end this was too confusing to extend to labels for exactly that reason, you might have multiple ones and it wasn't necessarily intuitive to users how the various notification settings would be applied (logical AND? logical OR? what about the "built-in" folders like Archive with custom labels?). So doing it only for folders, which are exclusive, removes that ambiguity. Sorry for the constraint but I don't expect this to change.
