### ISSUE TITLE
[Bug] DE translation of "Upgrade" is misleading

### ISSUE THREAD

**Issue by auipga** [ProtonMail/proton-mail-android#114]
**Describe the bug**
**Upgrade** in terms of a better product to buy is not called **Aktualisieren** in German.

**To Reproduce**
1. Open Android app
2. Open the left menu
3. Read

**Expected behavior**
Better translation or no translation at all. Upgrade is a well known word and often used in German language. [1]

**Screenshots**
![photo_2021-10-02_12-31-51](https://user-images.githubusercontent.com/876689/135712619-8a380001-b8b0-4fec-84bd-134e34c15fd5.jpg)

**Smartphone (please complete the following information):**
- doesn't matter

**Additional context**
[1] https://de-en.dict.cc/?s=upgraden

**Comment by kylekatarnls** [comment]
Thanks. Translations added in our system so it will be permanent (as `app/src/main/res/values-de/strings.xml` is regenerated automatically).

**Comment by auipga** [comment]
The item "Upgrade" is not in the menu anymore. -> obsolete
