### ISSUE TITLE
Lack of any communication

### ISSUE THREAD

**Issue by Flam3z** [ProtonMail/proton-mail-android#128]
Are the devs super busy behind closed doors? This repo is not really updated as frequently, issues don't get responses at all and there isn't really any posting that I have found talking about it. I want to upgrade my plan but if a simple darkmode feature cant even get developed where would my money be going to then? I hope a developer responds to this, I do not mean what i say in any way disrespectful or hateful.

**Comment by Stuie** [comment]
This seems like a really big issue to me.

I've been considering implementing some of the requested changes here on GitHub, but I see that barely any PRs get merged, lots of issues remain unanswered.

Dark mode, for example, has an implementation in PR right now. Coincidentally, it's one of the only PRs with a contributor response indicating that this GitHub repo is just a remote to be pushed to now and then, and there's no easy way to accept contributions from it.

Are contributions actually wanted here, or are people just wasting their time trying to help out?

**Comment by Flam3z** [comment]
I hope a response happens soon at least so I can understand if the devs are either sick or just very busy with others things so the community can understand the current situation.

**Comment by Manodiestra** [comment]
Looks like they have a lot of dev positions open. Maybe they just need some help.
https://careers.protonmail.com/#positions

But the issue mentioned here is valid. I posted an issue recently, then after combing through the existing issues, realized that it has been an open issue for nearly a year without any acknowledgement from a dev. You can see where I've mentioned it in previous issues I duplicated.
https://github.com/ProtonMail/proton-mail-android/issues/140

**Comment by Manodiestra** [comment]
The most recent commit to this repo is two months old. There's NO WAY this is Proton's main repo for their Android app. They have obviously abandoned the open source community on this project. They are no longer trustless and you must take their word for it when they say they care about your privacy.

In my opinion, the only way to trust software is in a trustless model, such as open source software.

Sorry, Proton. I'm going to be taking my privacy concerns somewhere else, unless you can come clean.

For all we know, Proton has signed a deal with Google smuggling user metadata to line their pockets on top of what they get from their subscribers.

**Comment by Manodiestra** [comment]
Thanks for the response. I understand not wanting to leak new logos and assets. In the future, it would be nice to get some communication before/during these transitions rather than going completely dark. It doesn't look good. Let the news (good or bad) be spread on _your_ terms, rather than leaving us all guessing.

Being Open Source is an absolute requirement if you want trust from people seeking privacy.
