### ISSUE TITLE
Consistent crashing when refreshing, changing folders, or opening unread emails

### ISSUE THREAD

**Issue by jwflory** [ProtonMail/proton-mail-android#14]
* Device: Motorola moto x4
* Android: 9 (PPWS29.69-39-6-6)
* ProtonMail version: v1.13.1 (711)

The app crashes frequently for me in day-to-day use. Certain actions like deleting an email, refreshing a folder, changing a folder, and sometimes opening an unread email cause ProtonMail to crash. I end up at my home screen. I cannot figure out exactly what criteria triggers the crashing because it doesn't happen all the time. But it is at least once or twice a day when the app becomes unusable.

**Comment by mpemer** [comment]
This happens to me too, primarily when deleting email. It always happens when I delete using the trash can icon in message view. It occasionally happens when I swipe to delete in folder view. The crash does not occur instantaneously, but after delete action is done and at some point during refresh.

**Comment by 4face-studi0** [comment]
@jwflory Did you check it with latest beta releases? It should be fixed

**Comment by jwflory** [comment]
I am running App Version 1.13.8 (726), but I have not noticed the crashing for some time. I am content with closing this since I opened it, but let me know if you want additional feedback.
