### ISSUE TITLE
[Bug] Duplicate notifications after message read/delete

### ISSUE THREAD

**Issue by tfardet** [ProtonMail/proton-mail-android#143]
**Describe the bug**
Once an email notification arrives on the Android app, an interaction with the email (either reading it or deleting it) triggers a second notification that is blank save for the recipient field.

**To Reproduce**
1. Receive an email on the Android app
2. Click on delete/trash (I use the French interface so I don't know what it is in English)
3. A new blank notification arrives a few seconds later

This can also be reproduced by reading the email, for example in Thunderbird on desktop (using the bridge).

**Expected behavior**
No additional notification arrives.

**Screenshots**
![image](https://user-images.githubusercontent.com/79037344/159962608-40994b94-0268-4227-8404-314673c73af7.png)

**Smartphone (please complete the following information):**
 - OS: Lineage 18.1 + Microg
 - Version 1.13.40 from F-droid

**Comment by rtyler** [comment]
I am also seeing this and have been for the last two versions. I recently upgraded to 1.13.40 hoping it would go away but it does not. :(

**Comment by tfardet** [comment]
Any news on that?
Does anyone know the cause or a quickfix?

**Comment by darkvadd7** [comment]
I still have the bug too. Any news?

**Comment by riccbos** [comment]
I found out that the F-Droid version of the app is unofficial and is missing an update. Just download the Play Store version (I'm on 1.13.40 (790) ) and it should work

**Comment by tfardet** [comment]
Thanks for the tip.
It seems the versioning on GitHub is not up-to-date which is why the unofficial app on Izzysoft's F-droid repo is lagging behind (as it relies on the GitHub repo.
So it would be nice if Protonmail devs could actually publish the code :)

**Comment by tfardet** [comment]
With the new release, this has been picked-up on the Izzy-droid repo, so closing.
