### ISSUE TITLE
Build error: The file name must end with .xml or .png

### ISSUE THREAD

**Issue by leomeyer** [ProtonMail/proton-mail-android#15]
Hello,

I am using Android Studio 3.6.3 with the Kotlin plugin 1.3.72-release-Studio3.6-1 on Windows 7 64 bit. I have just updated from a fairly old version (1. something) if this is relevant.
I needed to create an empty privateConfig/private.properties file to fix the error reported in issue #3.
During sync I get the following warning: "This project uses Gradle KTS build files which are not fully supported. Some functions may be affected."
There are also some warnings about deprecated project options.

Then, an error occurs during building: 
In tokenAutoComplete/tokenAutoComplete-example/src/main/res/drawable/tmp_2816003434625435209.tmp:
"The file name must end with .xml or .png"

I don't know whether this error is related to the above warnings. Any hints on how to fix this?
Thank you

**Comment by 4face-studi0** [comment]
Hello, that file does not belong to our code. I have no clue where it's coming from, you should just get rid of it, same as any other file that doesn't match with what that message says
