### ISSUE TITLE
SHA256SUM for APK on GitHub and Proton's website do not match

### ISSUE THREAD

**Issue by hspromo** [ProtonMail/proton-mail-android#156]
Is this a security risk? Both apps claim to be 3.0.0 but the files are not the same....

d54a4ecefc3e3f01b295180d20c1d8b3dd94f08f286e880d6062fabd32bb1244  ProtonMail-3.0.0.apk from git from https://github.com/ProtonMail/proton-mail-android/releases/download/3.0.0/ProtonMail-3.0.0.apk

47ee483ca17fb83bf786881d45157314c80bf44757bc6edfe3c76e4fe31729bb  ProtonMail-Android.apk from protonapps.com/protonmail-android

**Comment by carlosjeurissen** [comment]
Same issue is present in Proton VPN:
https://github.com/ProtonVPN/android-app/issues/85
