### ISSUE TITLE
Settings pagr for chrome opens every time i try to view email

### ISSUE THREAD

**Issue by ModdedGamers** [ProtonMail/proton-mail-android#17]
Basically the title, whenever i open ProtonMail or try to open an email, it opens the app settings page for Google Chrome. Not sure why this is happening, but it only happens with protonmail.

**Comment by 4face-studi0** [comment]
@ModdedGamers is Google Chrome enable on your device? Google Chrome contains updates for WebView, disabling it the default one shipped with the OS is used, but some Samsung - and probably some others - devices has a corrupted version of it.
If you desire to keep it disabled, you should install **Android System WebView** from the Google Play Store or alternative source

**Comment by ModdedGamers** [comment]
Webview is enabled and updated, as well as chrome.

**Comment by ModdedGamers** [comment]
If i disable chrome, the page still comes up, and It doesnt use webview.

**Comment by ModdedGamers** [comment]
It was actually a bug w/ work profiles lol. I installed shelter, and forgot to delete the work profile, and that screwed a lot of things up. Closing this now.
