### ISSUE TITLE
[Bug] Email notifications appear to not be working (app verison 3.0.2)

### ISSUE THREAD

**Issue by ItamiWasTaken** [ProtonMail/proton-mail-android#173]
**Describe the bug**
app does not notify user about new emails

**To Reproduce**
1. Send an email to protonmail address
2. No notification appears

**Expected behavior**
App to notify user about new emails

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Pixel 6]
 - OS: [Grapheneos, Android version 12L, google services are installed]

**Additional context**
it appears that notifications work on a device with microG installed, quite odd.
I will do some testing on my own and I will close the issue if I resolve this myself

**Comment by caveman1973** [comment]
Protonmail app needs Google Play Services for notifications to work. Strangely though, not even with that installed I was able to make it work.

If you want notifications to work, download the old version 1.13.40 here at GitHub.

**Comment by caveman1973** [comment]
I received an email from Proton explaining it was server side. They had to throttle down push notifications. I'm using 3.0.2 and it's working fine.

You can close this ticket.

**Comment by dR3b** [comment]
I have exactly the same problem. 

**Smartphone:** 
* Google Pixel 6 GrapheneOS
* Google Play Services installed

**Steps to reproduce the behavior:**
* Send an email to protonmail address
* No notification appears
