### ISSUE TITLE
Problem with Push Notifications on Android

### ISSUE THREAD

**Issue by rohitsuratekar** [ProtonMail/proton-mail-android#19]
I am having problem with push notifications on Android 9. I am using OnePlus5T with OxygenOS 9.0.11. Till date I have not received single push notification from the Protonmail app (1.13.1.711) Following things I have already checked.

- App is already whitelisted in 'Battery Optimization' settings
- There is no third party app (like Greenify) is hibernating it
- App has permission to work in the background
- Protomain app settings are proper and push notification is checked

I have even checked notification when app is in 'foreground'

**Comment by 4face-studi0** [comment]
@rohitsuratekar have you got any update about this issue? Has that been solved for you?

**Comment by rohitsuratekar** [comment]
@4face-studi0 : Yes. Since last update it is working properly now. Thank you :) 
Closing this issue.
