### ISSUE TITLE
App releases out of order on GitHub, causing update issues

### ISSUE THREAD

**Issue by loyl1** [ProtonMail/proton-mail-android#217]
On the releases page note that for some reason 3.0.11 is listed at the top of the page, like it is the latest release. 3.0.12 is listed below it as if it's the second most recent release.

This is not standard for GitHub, and causes update issues with users trying to auto update GitHub apps. I was able to manually update the app of course, but my phone still thinks I'm behind a release because 3.0.11 is displayed as the latest release. 

Expected behavior is the latest release is at the top of the releases page.

Not a huge thing.

I'm thankful for all the great work proton puts into all of it's software

**Comment by JohnOberhauser** [comment]
Also, version 3.0.13 is was uploaded to the google play store Mar 13, 2023, but 3.0.12 was only just added to the github release page 2 weeks ago.  There seems to be some sort of inconsistency.

**Comment by ZoricaStojchevska** [comment]
Hello, sorry for the inconvenience the order should be fixed now.
