### ISSUE TITLE
[Bug] Play Store v3.0.13, released mid-March, is not reflected by protonmail.com's APK or this source repo

### ISSUE THREAD

**Issue by miangraham** [ProtonMail/proton-mail-android#218]
Summary: Play Store release v3.0.13 has unknown content with no obvious corresponding changes in this repository or ProtonMail.com's downloadable APK. I can't tell from the outside whether this is an insider attack or a broken release process.

The Play Store version of the Android application appears to be ahead of all other data that's publicly available, including this repository. It has been in this state for over a month. This makes it impossible for outsiders to verify the latest application's behavior or build the latest version from source. Anyone using the Play Store has no visibility into what they're running. Anyone who avoids using the Play Store for installation, like myself, is stuck with an outdated build of the application and potentially left exposed to future vulnerabilities.

As of the time of writing, referencing [appbrain.com](https://www.appbrain.com/app/proton-mail-encrypted-email/ch.protonmail.android) for Play Store version history:
* Google Play Store's current APK version is 3.0.13, released March 7
* ProtonMail.com's current APK version is 3.0.12, released February 22
* Github.com repo tag versions 3.0.10-3.0.12 look mangled:

```console
$ git tag -l '3.0*'
3.0.0
3.0.1
3.0.11
3.0.12
3.0.2
3.0.4
3.0.5
3.0.6
3.0.7
3.0.9
```

3.0.10 does not appear at all. If there was a corresponding release (there was, according to appbrain.com), it may have somehow been overwritten by 3.0.12 which has no tag date besides the commit, and thus appears out of order about where you'd expect to see .10:

```console
$ git show 3.0.12
commit c98ccdff01754cc584145b2aea2c298317d828f6 (tag: 3.0.12, tag: 3.0.11)
Author: Zorica Stojchevska <zorica@protonmail.com>
Date:   Fri Dec 30 15:26:37 2022 +0100
```

3.0.11 is dated and therefore becomes the latest tag chronologically.

```console
$ git show 3.0.11
tag 3.0.11
Tagger: Zorica Stojchevska <zstojche@proton.ch>
Date:   Wed Jan 18 10:59:29 2023 +0000

(927)
commit c98ccdff01754cc584145b2aea2c298317d828f6 (tag: 3.0.12, tag: 3.0.11)
Author: Zorica Stojchevska <zorica@protonmail.com>
Date:   Fri Dec 30 15:26:37 2022 +0100
```

* Github.com release [3.0.12](https://github.com/ProtonMail/proton-mail-android/releases/tag/3.0.12) suddenly appeared two weeks ago, which must have been when the 3.0.12 tag was actually set/modified. This is a full month after the 3.0.13 release on the Play Store.
* The 3.0.12 APK in the Github.com release is identical to ProtonMail.com's 3.0.12 APK. This is good and means we can confirm source for the web download. It is trustable.
* I have no idea what is in the Play Store's 3.0.13 APK or where I can go to replicate or verify it.

The ad-hoc tagging makes it hard to get a clear signal as to what's going on with 3.0.13. Obviously it is signed by ProtonMail's Play Store key. Does someone bad have the key? Is the rest of the world simply lagging behind? I can't tell.

At best, the discrepancies above point to manual release work being done in an area that needs the consistency provided by automation in order to allow trust, verification, and correlation with known source. I'm grateful that ProtonMail exists as a pro-privacy provider, but uncertainty in this area risks undermining that quality. Help me continue to trust you. Thanks.

**Comment by ZoricaStojchevska** [comment]
Hello, sorry for this. We were a bit slow with the sync this time around. The process is mostly automated but it does require a manual trigger. But all releases should be aligned now.
