### ISSUE TITLE
[Feature Request] Sort trash by recently deleted

### ISSUE THREAD

**Issue by serkonda7** [ProtonMail/proton-mail-android#220]
**Is your feature request related to a problem? Please describe.**
Due to the swipe actions I sometimes delete a important mail by mistake.

**Describe the solution you'd like**
The trash should support sorting by "recently deleted", so I can immediately find the mail and restore it.

**Describe alternatives you've considered**
#67, #221

**Additional context**
While this feature would solve my main problem with swipe deleting, it would be in general useful for me (and hopefully others).

**Comment by marinomeneghel** [comment]
Thanks for raising this. 

This issue is likely to be impacted by other changes that we are already tracking in our backlog (eg. disable swipe actions / undo move operation).
