### ISSUE TITLE
Add an issue template

### ISSUE THREAD

**Issue by thgoebel** [ProtonMail/proton-mail-android#23]
**Steps to reproduce:**

1. Open a new issue in this repo.

**Expected behaviour:**

When you open a new issue, there should be an issue template.
Even better, separate templates for bugs and features.

See https://help.github.com/en/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests

**Actual behaviour:**

No issue template.

**Comment by darigovresearch** [comment]
We like this idea a lot, will make a pull request with separate issue templates as we have done that on our own open source repositories before.

Do you or any of the repository developers have any recommendations for what would be helpful to be contained in each template?

Will be using your above sections as a starting point for the feature request template.

**Comment by darigovresearch** [comment]
Have made a pull request #26 and instead have used the GitHub default text for the Bug and Feature Request Issue Template content and have adapted them to make them relevant to the repository

**Comment by jwflory** [comment]
I wanted to point out theGPLv3-licensed [OpenKeychain issue template](https://github.com/open-keychain/open-keychain/blob/master/.github/ISSUE_TEMPLATE.md) and [pull request template](https://github.com/open-keychain/open-keychain/blob/master/.github/PULL_REQUEST_TEMPLATE.md) written by @dschuermann for @open-keychain. I thought that was a good example of another open source Android app's issue/PR templates.
