### ISSUE TITLE
Some folders do not sync after bulk actions applied to inbox

### ISSUE THREAD

**Issue by jwflory** [ProtonMail/proton-mail-android#28]
# Summary

Some folders, like _Inbox_, show messages in the client that have been moved to other folders on the server

# Background

I ran a few bulk operations on my mailbox recently. I reduced a few thousand emails down to a handful. Most emails were moved to the _Archive_, _Trash_, or custom folders.

When I open the ProtonMail app, my _Inbox_ shows messages that were moved to other folders. When I open ProtonMail on web or via the ProtonMail Bridge, I do not see those messages in my inbox.

My first assumption is some kind of caching might be in play. But I'm not sure.

# Details

My Android environment:

* Android Version: _9_ (software variant `google_fi`, software channel `retus`)
* Device Model: _moto x4_
* ProtonMail Version: _1.13.1_
* From Google Play or F-Droid?: _Google Play_

# Outcome

Emails in a folder on client should match state of server

**Comment by jwflory** [comment]
I opened this without realizing it was a duplicate of #27. Different issue titles, same issue.

> **@thekix**:
> To solve the problem, I need to refresh local cache in the Android application and all is fine. But I cannot refresh the local cache every time.

Pressing _Empty Cache_ in Settings also fixed the issue for me. But this was not an obvious fix. Is there a way to avoid caching metadata like folders of emails? I'm not sure what a good default approach is here.

I know other mail clients like K-9 Mail solve this by exposing configuration values for how many emails are stored locally, how often the server is polled, how often certain data is refreshed, etc. But I think too many options are actually bugs, not features. The amount of configuration options in K-9 Mail can be overwhelming even to a more advanced user.

**Comment by 4face-studi0** [comment]
@jwflory we did some improvements on Sync engine, did you check it on latest Beta releases?

**Comment by jwflory** [comment]
What release is the beta release? I am running v1.13.8 (726) currently and still have this issue with actions to my mail from ProtonMail Bridge + Thunderbird.

**Comment by ZoricaStojchevska** [comment]
The latest Beta release is v1.13.9 (727), you could try that one and maybe update us if your issue was fixed.

**Comment by thekix** [comment]
Hello,

using Android, version 1.13.8 (726) and bridge v1.2.7, all is fine here. Thanks a lot!

For me, this bug could be closed.

Regards,
kix

**Comment by jwflory** [comment]
I will try to figure out where to find the beta release soon. For now, the issue definitely happens much less for me, but sometimes I have to refresh 2-3 times before the right messages display in the Android client (e.g. sometimes messages I already archived on Bridge+Thunderbird will appear even after I pull to refresh my mail the first time; the second or third time usually fixes it).

**Comment by 4face-studi0** [comment]
@jwflory please verify to be in the version mentioned above

**Comment by jwflory** [comment]
I'm not sure where/how to get access to the beta.

**Comment by 4face-studi0** [comment]
You can opt-in from the application page on Play Store

**Comment by ZoricaStojchevska** [comment]
@jwflory does this issue still happen for you? A few new version have been released since this ticket was last updated.

**Comment by jwflory** [comment]
I opted in to the beta and I remember applying some ProtonMail updates in the last week or two. This is fixed for me now, I am no longer able to replicate the bug.
