### ISSUE TITLE
Incomplete build instructions: missing privateConfig/private.properties

### ISSUE THREAD

**Issue by MihaiB** [ProtonMail/proton-mail-android#3]
Importing and building the project in Android Studio, [this line](https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/build.gradle#L160) from app/build.gradle fails with:
`/home/<username>/StudioProjects/proton-mail-android/privateConfig/private.properties (No such file or directory)`

If I create that empty file:
```bash
mkdir privateConfig
touch privateConfig/private.properties
```
then I can build and run the app: I see the sign-in screen.

I don't know what is an appropriate solution:
- add an extra step to the README "create an empty file privateConfig/private.properties"
Not so good: it's an extra manual step.
- make the script `gradlew` [here](https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/gradlew#L37) create that empty file if the remote is `github.com` and `$outputDir` (privateConfig) doesn't exist?
But the script seems to treat `privateConfig` as a private git repository: git cloning into it and copying `sentry.properties` out.

Also, I don't know if the empty file workaround suffices when running the app past the welcome screen.

Will you develop the project in this public repository, or will you only share the source code here from time to time but develop it in a private (GitLab?) repository?
Are you interested in contributions? This GitHub Issue aims to improve the instructions to allow someone unfamiliar with the code to build and run it.

**Comment by 4face-studi0** [comment]
Thank you for the report.

The code on GitHub is synced with the GitLab's `release` branch, so once something roll up to release, the code reaches this repo.

Contributions are very appreciated, but we will need to patch our `develop` branch with the commits from the PR, so it will take quite a while until the code will reach this public repo.

About `private.properties` and `sentry.properties` we will prepare an how-to asap. Basically they contains keys for 3rd parties ( like Sentry ) and much probably they will just print an error in the logcat, describing that a valid key is missing, without affecting the natural behavior of the application. 
But, as said, we will provide a guide asap.
Please be patient :)

**Comment by MihaiB** [comment]
Thank you for the kind response!

Feel free to close this issue according to your workflow (now when added to the team's internal task list; later when the updated guide is pushed to GitHub - this way it documents to others that the issue is noted and pending).

I would suggest mentioning briefly in the README that contributions are welcome and the workflow is that you develop internally and publish to GitHub on release.

No hurry from me, I just had a first look at your new repository. The brevity of the README is a plus: just a few instructions and it runs.
Perhaps the upcoming guide could mention briefly if the app is meant to run against the production ProtonMail backend with a user's main/proper/personal account and any recommendation (if there even exists one) for getting a test account without upsetting your systems that detect abuse. In case unusual activity results in blocking all of a user's free accounts, including the proper/main one (if that happens to be a free account). Though I'm properly over-cautious with this last point :)

**Comment by MihaiB** [comment]
Small update: the [problematic line](https://github.com/ProtonMail/proton-mail-android/blob/a8691147877729f142bd622fa5383d5a0f989438/app/build.gradle.kts#L56) is now in app/build.gradle.kts.

After importing the project, Android Studio's auto build fails with:
```
privateConfig/private.properties (No such file or directory)
```

**Comment by 4face-studi0** [comment]
!36

**Comment by 4face-studi0** [comment]
https://github.com/ProtonMail/proton-mail-android/pull/36

**Comment by MihaiB** [comment]
Solved! Now the project builds and runs in Android Studio without any extra steps.
Nice setup :) even someone without Android development knowledge can build and run the project very easily.
