### ISSUE TITLE
Removing the current text while renaming a folder makes the menu jump back.

### ISSUE THREAD

**Issue by arch-btw** [ProtonMail/proton-mail-android#31]
Hi ProtonMail,

I noticed this error on the Google Play version of ProtonMail (I haven't tested if the F-droid version has the same issue).

**Operating system:** LineageOS 16.0
**Android version:** 9.0

Video:

![2020_06_09_23_20_38_trim](https://user-images.githubusercontent.com/57669023/84203390-37522700-aa5e-11ea-8ba3-0bb8c2a8a144.gif)

**Comment by ZoricaStojchevska** [comment]
This is addressed in new 1.13.19 version, it be synced onto GitHub once it is released.
