### ISSUE TITLE
Feature Request: Add Dark Theme

### ISSUE THREAD

**Issue by Viper896** [ProtonMail/proton-mail-android#32]
This is one of the few apps that I use that doesn't follow my System's Color Theme (which is set to dark).  It would be nice to have the ability to switch between light and dark color themes.  Even better if it could just query what theme the device is using and use the systems default theme setting.

More information about Android's light/dark themes can be found here:
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

**Comment by darigovresearch** [comment]
Think this would be a really helpful feature, has there been any progress on this topic since the issue was first opened?

**Comment by nebeker** [comment]
The truth is, for a lot of people this isn't a nice to have feature - it's an accessibility feature for people with vision impairments. Yes, you can invert all colors on your device, but since most apps nowadays support dark modes, you might end up having to do that every time you switch to and from ProtonMail.

**Comment by KaKi87** [comment]
Hello,

Although I don't have vision impairment, I do need this feature because I just don't like blinding white.

Thanks

**Comment by KaKi87** [comment]
Also, the first time I asked for that feature was through the Play Store, back in 20**18**, and I was told the Proton team were "looking into it", so I'm having a hard time believing them now.

**Comment by darigovresearch** [comment]
Thanks @marinomeneghel for the guidance. Think that the accessibility issues raised above should mean that this should be taken as a priority if possible. Similar concerns have been raised in the web client - https://github.com/ProtonMail/WebClient/issues/173 Not sure if it needs to wait until V4 to be able to be implemented as an initial optional solution could be implemented and iterated on for the V4 release.

An issue has also been raised here - https://github.com/ProtonMail/design-system/issues/266

**Comment by gahfy** [comment]
Hi,

I just switched today to ProtonMail from GMail, and my first impression was about dark theme. I was exactly thinking the same about Dark Theme, but I also understand accessibility issues.

I'm Android Developer and would love to work on that feature, but would also like my PR to be approved, so maybe can discuss implementation here.

My idea:

* In the application settings section of the settings menu, add an item theme
* The user can choose between light, dark, or same as phone settings
* By default, the app is set in light mode

My belief is that this way, nothing changes about accessibility, but people who want to switch to dark mode are able to do so.

**Comment by gahfy** [comment]
Just made a first pull request (only for mailbox) just to know if it's going in the right direction ?
Maybe it would be preferable to do it by creating new styles in `ProtonTheme` (this would be OK for me, but would make the feature impossible to release before v4 is released)

**Comment by KaKi87** [comment]
> By default, the app is set in light mode

No, by default, the app should be set to system mode

**Comment by gahfy** [comment]
@KaKi87 Yes it is what have been done in the pull request I've made

**Comment by nebeker** [comment]
> @KaKi87 Yes it is what have been done in the pull request I've made

PR #101? From a low vision perspective, it looks pretty good. You could make the background a bit darker and the text a bit brighter for better contrast.

**Comment by gahfy** [comment]
Actually, for compliance, I used the existing default colors in the new palette

**Comment by nebeker** [comment]
OK, fair enough. That could be an extra theme for V4.

**Comment by darigovresearch** [comment]
@gahfy thank you very much for taking the time to make the pull request. Following the colour pallet would make it more likely to be merged. Now it is up to anyone from the Protonmail team to advise

**Comment by jahway603** [comment]
Some of us need a dark theme because due to visual accessability in order for us to be able to use this app.

**Comment by bartbutler** [comment]
@jahway603 the latest beta has this, which is coming via a staggered rollout.
