### ISSUE TITLE
Notifications do not work on Huawei & Honor phones without Google Mobile Services

### ISSUE THREAD

**Issue by sml12** [ProtonMail/proton-mail-android#33]
Please update app to enable android push notifications for Huawei & Honor phones without Google Mobile Services (Google Firebase Cloud Messaging). Please enable for Huawei Push Service in Huawei Mobile Services.

**Comment by posthello-code** [comment]
Also appears to be an issue on motorolla when google services disabled.

**Comment by marinomeneghel** [comment]
@sml12 Currently notifications are sent through FCM, so they won't work on any device without Google Play Services.

A wider topic is about integrating / implementing a different solution to handle push notifications, tracked by #7 

Can we close this?

**Comment by xster** [comment]
I think this can be duped into #7. There aren't anything differentially needed for Huawei phones (which support solutions like https://github.com/Telegram-FOSS-Team/Telegram-FOSS).

**Comment by 4face-studi0** [comment]
Correct, thanks @xster
