### ISSUE TITLE
Missing plural forms

### ISSUE THREAD

**Issue by mKoonrad** [ProtonMail/proton-mail-android#4]
Missing plural forms for few (2-4, 22-24, etc) and many (5-19, 100 etc).
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L152
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L259
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L164
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L405
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L445
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L588
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L993
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L1085
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L1100
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L1101

**Comment by mKoonrad** [comment]
@4face-studi0 Any new info about fixing this issue? Any ETA?

**Comment by marinomeneghel** [comment]
Hi @mKoonrad,
thanks for reporting this! 

Some of the issues you mentioned should have been resolved already. Could you please double check and let us know whether there are still any pending ones?

**Comment by mKoonrad** [comment]
@marinomeneghel 

I checked it once time based on latest file. You still need to fix:
https://github.com/ProtonMail/proton-mail-android/blob/f06fdcbb2d37a69cce06e6b8fe087762a653ef3c/app/src/main/res/values/strings.xml#L133
https://github.com/ProtonMail/proton-mail-android/blob/f06fdcbb2d37a69cce06e6b8fe087762a653ef3c/app/src/main/res/values/strings.xml#L349
https://github.com/ProtonMail/proton-mail-android/blob/f06fdcbb2d37a69cce06e6b8fe087762a653ef3c/app/src/main/res/values/strings.xml#L378
https://github.com/ProtonMail/proton-mail-android/blob/f06fdcbb2d37a69cce06e6b8fe087762a653ef3c/app/src/main/res/values/strings.xml#L507
https://github.com/ProtonMail/proton-mail-android/blob/f06fdcbb2d37a69cce06e6b8fe087762a653ef3c/app/src/main/res/values/strings.xml#L967
⬆️ Separate plural forms for hours and minutes
https://github.com/ProtonMail/proton-mail-android/blob/f06fdcbb2d37a69cce06e6b8fe087762a653ef3c/app/src/main/res/values/strings.xml#L968
