### ISSUE TITLE
Can i use ProtonVPN in China?

### ISSUE THREAD

**Issue by docd3514** [ProtonMail/proton-mail-android#41]
hi guys i'm planning to go to China for business purpose and i want some input to you all that have been to Mainland China using ProtonVPN

**Comment by 4face-studi0** [comment]
I guess you're in the wrong repo 🙂
https://github.com/ProtonVPN/android-app

Anyway for this kind of question I believe you should contact the customer support, as us developer really don't have a clue about China bans.

FYI: I've been in China and it was working flawlessly until the 70th anniversary of the Republic last October when they erased any VPN service and they had to find other solutions 😅 
But ye, CS might help you better
