### ISSUE TITLE
[Bug] Number of letters is different in the web & android version

### ISSUE THREAD

**Issue by IT-Tool** [ProtonMail/proton-mail-android#45]
Why the number of letters is different in the web from the android version?
![IMG_20201019_171314_698.jpg](https://user-images.githubusercontent.com/53435741/96462759-7adf4d80-1215-11eb-911d-4e519347b9cc.jpg)

In the web version, e-mails with the same title are grouped into one. But even this does not help to make sure that the number of emails is displayed correctly (you can see it in the second screenshot). Only a lot of questions remain!
![IMG_20201019_171337_716.jpg](https://user-images.githubusercontent.com/53435741/96462831-90547780-1215-11eb-9ba7-830498d620d4.jpg)

**Comment by ZoricaStojchevska** [comment]
This counters are referencing the **unread** messages that you have in the folder. That being said the web app is using conversation mode which like you said groups the messages, when this is enabled on the web, because the Android app doesn't have this feature the counters on the mobile app will always be higher. So in the last screenshot it seams that in this folder from 147 messages, 2 are unread still.

**Comment by IT-Tool** [comment]
> This counters are referencing the **unread** messages that you have in the folder. That being said the web app is using conversation mode which like you said groups the messages, when this is enabled on the web, because the Android app doesn't have this feature the counters on the mobile app will always be higher. So in the last screenshot it seams that in this folder from 147 messages, 2 are unread still.


Ok. But in the web version, the number of unread messages is 109 (in the second screenshot), while the mobile app displays 71 unread messages. Is this still fine?
Okay, let's compare by folder "All mail" (differ again in quantity!)
If we are talking about all letters, they do not have to be grouped (in "All mail" folder)!

Can there be at least one folder with the same number of emails to understand that everything is synchronized correctly?

**Comment by 4face-studi0** [comment]
As @ZoricaStojchevska said, web shows the count of unread conversation, on the other side Android, non having that feature yet, show the count of unread messages

**Comment by marinomeneghel** [comment]
@IT-Tool Thanks for raising this.
As there was an explanation for the behavior being reported here, is this issue still needed?

The upcoming implementation of the conversation mode is also tracked [here](https://github.com/ProtonMail/proton-mail-android/issues/12)
