### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mKoonrad** [ProtonMail/proton-mail-android#5]
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L275
Should be `not allowed`

**Comment by 4face-studi0** [comment]
This has been fixed and will be available in next beta. **This repo will reflect the fixes once the code reach the release channel**

**Comment by mKoonrad** [comment]
@4face-studi0 Great. Btw I found another typo:
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L792

After coding you have `%1$s < %2$s> wrote:`. It should be `%1$s <%2$s> wrote:`.

**Comment by 4face-studi0** [comment]
@mKoonrad thank you
