### ISSUE TITLE
[Bug] App sometimes attempts to send outgoing e-mail twice when on a weak connection, leaves a draft in the Drafts folder that can't send and that you can't delete

### ISSUE THREAD

**Issue by Ammako** [ProtonMail/proton-mail-android#62]
**Describe the bug**
Not entirely sure how to call it, but I've run into an error that makes the app try to send a mail more than once. When that happens, the mail doesn't show up in the Sent folder, instead it stays in Drafts, where it says "sending message..." with a loading icon, which never completes, and every few seconds I get a notification telling me that the message failed to send because it has already been sent. If I try to remove the "ghost" draft, I get "Error while deleting some messages. Some of the selected messages are in sending process?!"

After a little bit, it eventually manages to clear itself up, and it lets me delete the "ghost" draft.

**To Reproduce**
I don't have clear reproduction steps, because I'm not certain what causes it. But it might be a combination of unstable connection, and accidentally double-tapping the Send button. I'm sending e-mails to a non-protonmail address as well, which may or may not make a difference.

**Expected behavior**
If the app knows that a message has already been sent, it should stop trying to send the "ghost" draft and clear it, instead of leaving it there and trying to send it again and again. It should self-correct when network-related errors happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/43770697/104641175-57eff880-56a1-11eb-8d21-1f735b897800.png)

(If I can get it to happen again, I'll include a screenshot of the error notification. I didn't think of taking a screenshot of it and it hasn't happened again yet.)

**Smartphone (please complete the following information):**
 - Device: Nexus 5
 - OS: Android 7.1.2
 - Version 1.13.24 (751)

**Additional context**
I've confirmed that when this happens, the message *does* get sent properly, even if it's not very clear.

**Comment by Ammako** [comment]
![image](https://user-images.githubusercontent.com/43770697/111077427-19bb5d80-84c7-11eb-9477-999e94217b92.png)

This is the notification that shows up over and over.

Happened on a weak network connection... the email seems to fail to send because of network connectivity issues. I only tapped Send once, then sat on my inbox waiting for "Message Sent" to show up. But it never did, instead the outgoing email remained in Drafts and it kept complaining that this e-mail had already been sent.

After a while, it clears itself up somehow, and it removes itself from drafts, but the sent email doesn't show up in Sent, which makes it hard to tell if the email has been sent or not.

**Comment by marinomeneghel** [comment]
@Ammako thanks for the detailed report. 

We included a mitigation for this issue in the latest beta build (764) which is currently being distributed, if you manage to give it a go we're looking forward to hear any thoughts!

**Comment by Ammako** [comment]
It's going to be difficult to say whether or not this was properly fixed, given that it only rarely happens and can't be reproduced very easily, but I'll close this for now, and if it happens again, I can just reopen.

**Comment by Ammako** [comment]
Right now, the app crashed entirely when my connection was dropping and I tried to send. Now the message is stuck in drafts and won't send.

After a few minutes it clears itself up saying that the message failed to send, but when I try to re-send it just loads forever once again, and never sends.

**Comment by Ammako** [comment]
Crashed again when trying to write a reply, I hadn't sent it though. But it left two drafts in my drafts folder, both empty.

**Comment by marinomeneghel** [comment]
Thanks for the info. 
The fact that it happened also when not sending makes it odd, as we might be looking at different issues here. Any additional details you can share? Anything that might help reproducing is valuable, such as level of network connectivity, internal / external recipient, presence of attachments and so on.

**Comment by Ammako** [comment]
Network connectivity might be hard to say, because signal to the access point is fine, there's just *something* causing the connection to drop. So it shows full signal on my status bar but suddenly I don't have connection, and after a few moments wifi icon disappears as my phone realizes the connection died.

External recipient, no attachments.

**Comment by marinomeneghel** [comment]
Since you mention an Access Point I assume you're referring to a home Wi-Fi connection, right? 
Do you also have mobile coverage in the moment in which this happens? Whatever the case with connectivity the app shouldn't crash, there's no discussing that, but I'm wondering whether this might be some specific issue on your device.

Under normal circumstances I'd expect mobile network to seamlessly take over in case Wi-Fi drops, but here you seem to be experiencing an actual loss of connectivity, correct?

**Comment by Ammako** [comment]
Mobile data is off at all times when I'm at home, to avoid accidentally using data when wifi unexpectedly drops.

**Comment by Ammako** [comment]
Can we just get a menu option to cancel the sending of an email, so I can at least get it un-stuck when it insists on forever sending? Because otherwise the only way I can clear it is to clear app data and log back in... because even force-stopping the app just has the message still stuck attempting to send once I reopen the app.

Takes several minutes and eventually I get a "failed to save online draft http 422: unprocessabke entity" alongside with a notification telling me that the message failed to send. But sometimes I can't really afford to wait 5 minutes for it to fail on its own (and sometimes it takes way longer than that.)

**Comment by Ammako** [comment]
Also, I've been getting message send failure notifications, even when my message actually sent just fine everal minutes prior.

**Comment by marinomeneghel** [comment]
@Ammako thanks for your suggestion and for adding these details. We are re-opening this issue to verify what exactly isn't working and evaluate the options, will keep this thread updated as soon as we have news

**Comment by Ammako** [comment]
None of this really matters tbh, because new mobile app is announced for later this summer and I'd much rather focus go towards the replacement mobile app instead of spending dev time on a soon-to-be obsolete app.
