### ISSUE TITLE
[Bug] Local storage limit "Unlimited" doesn't work

### ISSUE THREAD

**Issue by Ammako** [ProtonMail/proton-mail-android#63]
**Describe the bug**
Changing the local storage limit to Unlimited doesn't actually do anything. You try to set it to Unlimited, and it just reverts back to the previous setting.

**To Reproduce**
1. Go to Settings --> Account settings
2. Click on Local storage limit
3. Press on "Unlimited" to set the storage limit to Unlimited
4. Go back to the previous page, and it didn't save. It's still set to what it was previous set to.

**Expected behavior**
It should be possible to set the Local storage limit to Unlimited.

**Smartphone (please complete the following information):**
 - Device: Nexus 5
 - OS: Android 7.1.2
 - Version 1.13.24 (751)

**Comment by Peter4487** [comment]
FYI this is still a bug in 1.13.29

**Comment by Peter4487** [comment]
I am still seeing this in 1.13.39 (786)
