### ISSUE TITLE
[Feature Request] Disable swiping actions

### ISSUE THREAD

**Issue by SpikyPillow** [ProtonMail/proton-mail-android#67]
**Is your feature request related to a problem?**
I do not like swiping gestures, they are very annoying to me, I'd rather have no actions happen, and no sliding of the emails to occur.

**Describe the solution you'd like**
I'd like an additional option to disable the swiping gestures. This could be implemented as another swiping option in settings, or it could be a "disable swiping gestures" checkbox instead. Ideally, this would stop the emails from sliding left and right at all when you swipe them, but even just having an option for them to do nothing would be good.

**Comment by kylekatarnls** [comment]
It sounds feasable and checked some other mail clients, they have a "no actions" checkbox in settings so I guess we should do that this way.

**Comment by sedlund** [comment]
I like the swiping actions, but I admit I have accidentally swiped many a message to delete or spam in the PM client.  Maybe there is some tuning to the swiping action to make these mistakes less easy?

**Comment by LeTempus** [comment]
It is also a feature I am looking after. Feel free to assign it to me. I will work on it.

**Comment by Forage** [comment]
Sorry for the "me too", but I feel that the reason for having a way to disable swipe actions has not been stressed enough.

It's too easy to accidentally perform a swipe action. A small touch at only the edge of the screen is easily made and already sufficient to delete emails.
Yes, an undo is offered, but this is not sufficient as a fall-back. The undo button is shown for only a short amount of time. The button is only effective of you conciencely perform a swipe action. If it was an accident you have almost no time left to act after you realise you accidently made a swipe movement. That is if you even notice it at all. In case of the latter or when you're too late to respond you have no easy way left to find back the message you e.g. deleted if this was an older message, as it won't show at the top of the trash folder list.

All this makes the swipe action on lists a bad UI design pattern. It should only be activated by choice at first run of the app e.g.

The UI refresh in the latest beta unfortunately still includes the action activated by default with no option to disable it.
Please reconsider this behaviour.

**Comment by xIUPITERx** [comment]
Any updates?

**Comment by LeTempus** [comment]
@xIUPITERx Unlikely to be merge or implemented soon I think. Plus with the new UI that has been released for the whole Proton ecosystem, they must've included some backend change that would make the MR I opened unusable. I didn't have time to dive into the code again, I'll try

**Comment by marinomeneghel** [comment]
This didn't make it to getting prioritised yet. We'll keep track of it in our backlog and come back when there are updates.
