### ISSUE TITLE
[Bug] Infinite loading when no starred messages

### ISSUE THREAD

**Issue by agonist** [ProtonMail/proton-mail-android#68]
**Describe the bug**
When having no starred messages, the starred messages screen is displaying an infinite loader instead of the empty messages view.

**To Reproduce**
1. Make sure you have no starred messages
2. Click on the starred message from the drawer menu
3. The loader will be displayed and never disappear

=> Reproduce every time very easily.

**Expected behavior**
The "No messages" screen should be displayed the same way it is displayed for other inbox types.

**Smartphone (please complete the following information):**
 - Device: Pixel 3 XL / Any emulator 
 - OS: Android 11
 - App Version: 1.13.25

**Additional context**

After a little investigation, I can see that since the starred inbox is handled differently than the others.

When the `RefreshEmptyViewTask` is called the messages count for starred inbox will always be `null` and by consequent the `mailboxActivity?.refreshEmptyView(messageCount)` will never be called and the flow will end in `MailboxActivity.onMailboxNoMessages` without the view being refreshed.

A quick fix could be to add a call to `refreshEmptyView(0)` at the end of the `onMailboxNoMessages` function.

**Comment by MarekTrze** [comment]
I fix this bug, changes are in https://github.com/ProtonMail/proton-mail-android/pull/78

**Comment by bentenjamin** [comment]
Can this bug be closed?
