### ISSUE TITLE
[Feature Request] Option to unbundle notifications

### ISSUE THREAD

**Issue by sedlund** [ProtonMail/proton-mail-android#70]
**Is your feature request related to a problem? Please describe.**
I have an Amazfit Bip smart watch.  When I receive the first push notification for a new email I get a useful notification sent to my watch and can decide to read or ignore it at the moment.

If I ignore it any subsequent emails received I only receive "2 new emails" "3 new emails" etc. pushed to my watch.  To get a useful notification thereafter on my watch I have to open the app to clear the notification bundle.

**Describe the solution you'd like**
I would like each notification to include the email from/subject

**Comment by sedlund** [comment]
Signed up for Tutanota to find out if they implement this properly, they make you wait two days to use the service after sign up -- fun  But they also fail at notifications.

https://github.com/tutao/tutanota/issues/557

**Comment by marinomeneghel** [comment]
Hey @sedlund , Thanks for raising this!
it seems similar to https://github.com/ProtonMail/proton-mail-android/issues/56, isn't it? If so, we could close this one and add any additional context to the other issue to keep all the info in one place.

**Comment by sedlund** [comment]
@marinomeneghel yeah that is the same issue.  I will comment there about the watch notifcation issue.
