### ISSUE TITLE
[Feature Request] Make swipe action customizable

### ISSUE THREAD

**Issue by BonaBeavis** [ProtonMail/proton-mail-android#73]
Swipe left to mark as spam and swipe right to delete? I am coming from google mail, where the spam filter works and you never delete your mail. So two seldom used actions are one swipe away and archiving an email does take three touches.

**Comment by Ammako** [comment]
https://protonmail.com/support/knowledge-base/swipe-action-manage/

**Comment by BonaBeavis** [comment]
Sorry, I do not know how I overlooked this.
