### ISSUE TITLE
[Feature Request] Add "Mark Read" button to notification

### ISSUE THREAD

**Issue by HeyBanditoz** [ProtonMail/proton-mail-android#77]
**Is your feature request related to a problem? Please describe.**
When I'm at my computer, I usually have the bridge with my local client open. When I get an email, I get a notification there and on my phone.

**Describe the solution you'd like**
I'd like to be able to quickly mark an email as read from without clicking on the email from the Android app.

**Describe alternatives you've considered**
Clicking into the email on Android, which can take a while.

**Additional context**
See a hastily drawn markup here.
![Screenshot_20210317-163130__01](https://user-images.githubusercontent.com/7574664/111547701-2813ae80-873f-11eb-8e43-618d03385690.jpg)

**Comment by marinomeneghel** [comment]
@HeyBanditoz thanks for raising the improvement.

This is already being tracked here https://github.com/ProtonMail/proton-mail-android/issues/30

**Comment by Ammako** [comment]
What about #50, though? It's been a few months since.

**Comment by marinomeneghel** [comment]
You are right on that, we've had different priorities that didn't allow us to invest into the "mark read" functionality quite yet.

We're tracking this in our internal improvements backlog as well but I can't provide a timeline on when we'll be able to tackle it.

**Comment by mizzunet** [comment]
This issue may be closed #30 #50
