### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by DonoV81** [ProtonMail/proton-mail-android#82]
Describe the bug
Startup crash / failure to launch, only the logo screen is shown for a few seconds and then the app is quickly closed.

Smartphone (please complete the following information):

Device: Samsung a6+
OS: Android 10
Version 1.13.29, all versions
Additional context
Couldn't include logs, since the app won't launch

**Comment by marinomeneghel** [comment]
Hi @DonoV81 ,
thanks for reporting this. 

I would suggest you to contact our customer support in this regard, as they have more visibility over similar issues that might have happened and can better support you through the steps to troubleshoot this
