### ISSUE TITLE
Add a redirection to the Proton Guidelines in the README

### ISSUE THREAD

**Issue by LeTempus** [ProtonMail/proton-mail-android#84]
I wanted to read the Proton Guidelines before starting to contribute to the project but I had a hard time finding them. Maybe including a redirection/link to them directly in the README would be nice for the future people wanting to contribute?

**Comment by Ammako** [comment]
Wait, what?

[Am I missing something?](https://github.com/ProtonMail/proton-mail-android/blob/release/README.md#contributions)

**Comment by LeTempus** [comment]
Ah, my bad. I thought there were more to it!
