### ISSUE TITLE
[Question] ProtonMail APK update notifcation

### ISSUE THREAD

**Issue by julianfairfax** [ProtonMail/proton-mail-android#94]
Hi,
If I install the ProtonMail APK from https://protonapps.com/protonmail-android# will I get some kind of notification when an update is released? Thanks for your help!

**Comment by akc3n** [comment]
> Hi,
> If I install the ProtonMail APK from https://protonapps.com/protonmail-android# will I get some kind of notification when an update is released? Thanks for your help!

No. You have to manually check https://github.com/ProtonMail/proton-mail-android/releases  
I actually came here just now to post a feature request for enhancement to https://protonapps.com to include the current release version number in listings of their apps.

**Comment by julianfairfax** [comment]
Hopefully this app is added to F-Droid soon. Thanks for your help!

**Comment by Ammako** [comment]
> You have to manually check https://github.com/ProtonMail/proton-mail-android/releases

![image](https://user-images.githubusercontent.com/43770697/120729260-afee9680-c4ac-11eb-8151-7bfb422f7f76.png)

;p
